# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json
PackageIdentifier: SnlperStripes.ClaudeAccountSwitcher
PackageVersion: 0.1.2
InstallerType: portable
Commands:
  - claude-account-switcher
ReleaseDate: 2026-09-27
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/SnlperStripes/claude-account-switcher/releases/download/v0.1.2/claude-account-switcher-windows-amd64.exe
    InstallerSha256: AB8284375F3395D49AD49B11738FCAB7D6BB9A3A2EF7E7EB7633205D49F3E6E1
ManifestType: installer
ManifestVersion: 1.10.0
